
server:
  port: 18080
spring:
  application:
    name: smdemo
  datasource:
    port: 3306
    host: 192.168.43.201
    shemae: sakila
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.shemae}?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mysql123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      max-active: 5
      min-idle: 5
      initial-size: 5
      max-wait: 60000
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*-mapper.xml
logging:
  config: classpath:log/logback.xml
